describe('Contact form tests', () => {
    beforeEach(() => {
        cy.visit('/contact');
    });

    it('Allows submitting data and shows success', () => {
        cy.intercept('POST', '/api/contact', {
            statusCode: 200,
            body: {}
        });

        cy.getByDataCy('input-text-contact-name').type('Cypress Test');
        cy.getByDataCy('input-text-contact-company').type('Cypress Test Company');
        cy.getByDataCy('input-text-contact-email').type('cypresstest@cypresstestcompany.com');
        cy.getByDataCy('input-text-contact-message').type('This request was generated by a Cypress e2e test.');

        cy.waitForStableDOM({pollInterval: 500, timeout: 10000});
        cy.getByDataCy('button-contact-submit').should('be.visible').click();

        cy.waitForStableDOM({pollInterval: 500, timeout: 10000});
        cy.getByDataCy('alert-contact-success').should('be.visible');
    });

    it('Allows submitting data and shows error', () => {
        cy.intercept('POST', '/api/contact', {
            statusCode: 502,
            body: {}
        });

        cy.getByDataCy('input-text-contact-name').type('Cypress Test');
        cy.getByDataCy('input-text-contact-company').type('Cypress Test Company');
        cy.getByDataCy('input-text-contact-email').type('cypresstest@cypresstestcompany.com');
        cy.getByDataCy('input-text-contact-message').type('This request was generated by a Cypress e2e test.');

        cy.waitForStableDOM({pollInterval: 500, timeout: 10000});
        cy.getByDataCy('button-contact-submit').should('be.visible').click();

        cy.waitForStableDOM({pollInterval: 500, timeout: 10000});
        cy.getByDataCy('alert-contact-error').should('be.visible');
    });
});
