import React, {useEffect, useState} from 'react';
import {Container, Paper, Typography} from '@mui/material';
import {styled} from '@mui/material/styles';
import Head from 'next/head';
import {SubHeader} from '../ui/page-elements/subheader/SubHeader';

export default function PrivacyPolicy() {
    const [hostname, setHostname] = useState('');

    useEffect(() => {
        setHostname(typeof window !== 'undefined' && window.location.hostname ? window.location.hostname : 'salienttechconsulting.com');
    }, []);

    const titleText = 'Privacy Policy';
    const metaDescriptionText = `Salient Technology Consulting's Privacy Policy.`;
    const headerText = 'Privacy Policy';
    const headerSubText = 'Salient Technology Consulting LLC Privacy Policy';

    const BodyTypography = styled(Typography)(({theme}) => ({
        ...theme.typography.body2,
        color: 'inherit',
        flexGrow: 1,
        fontWeight: 300,
        justifyContent: 'center',
        textAlign: 'left',
        textDecoration: 'none',
        whiteSpace: 'pre-line'
    }));

    const BodyHeaderTypography = styled(BodyTypography)(() => ({
        fontWeight: 700
    }));

    return (
        <>
            <Head>
                <title>{titleText}</title>
                <meta name='description' content={metaDescriptionText} />
            </Head>
            <SubHeader headerText={headerText} headerSubText={headerSubText} />
            <Container maxWidth='md'>
                <Paper sx={{px: 2, py: 2, mb: 4, mt: 6}} elevation={5}>
                    <BodyHeaderTypography>Privacy Policy</BodyHeaderTypography>
                    <BodyTypography>
                        {`
Effective Date: December 04, 2023

Thank you for visiting www.${hostname}. This Privacy Policy outlines how we collect, use, disclose, and safeguard your information when you use our website or services.

`}
                    </BodyTypography>
                    <BodyHeaderTypography>Information We Collect:</BodyHeaderTypography>
                    <BodyTypography>
                        {`
We may collect personal information, including but not limited to your name, email address, and other relevant details when you voluntarily provide them through forms or communications on our website.

Additionally, our website uses Google Analytics, a web analytics service provided by Google Inc. Google Analytics utilizes cookies to help us analyze how users interact with our site. The information generated by these cookies (including your IP address) will be transmitted to and stored by Google on servers in various locations. Google uses this information for the purpose of evaluating your use of the website, compiling reports on website activity, and providing other services relating to website activity and internet usage.

`}
                    </BodyTypography>
                    <BodyHeaderTypography>How We Use Your Information:</BodyHeaderTypography>
                    <BodyTypography>
                        {`
We use the information collected, including Google Analytics data, to improve our website, personalize your experience, and analyze trends and user behaviors.

`}
                    </BodyTypography>
                    <BodyHeaderTypography>Cookies:</BodyHeaderTypography>
                    <BodyTypography>
                        {`
Cookies are small data files stored on your device. Our website uses cookies for various purposes, including but not limited to providing a customized user experience and analyzing website traffic through Google Analytics.

`}
                    </BodyTypography>
                    <BodyHeaderTypography>Third-Party Disclosure:</BodyHeaderTypography>
                    <BodyTypography>
                        {`
We do not sell, trade, or otherwise transfer your personally identifiable information to third parties unless we provide you with advance notice.

`}
                    </BodyTypography>
                    <BodyHeaderTypography>Opting Out of Google Analytics:</BodyHeaderTypography>
                    <BodyTypography>
                        {`
You can opt out of Google Analytics by installing the Google Analytics Opt-Out Browser Add-On, available at `}
                        <a href='https://tools.google.com/dlpage/gaoptout' style={{color: 'inherit'}}>
                            https://tools.google.com/dlpage/gaoptout
                        </a>
                        {`.

`}
                    </BodyTypography>
                    <BodyHeaderTypography>Your Consent:</BodyHeaderTypography>
                    <BodyTypography>
                        {`
By using our website, you consent to our Privacy Policy.

`}
                    </BodyTypography>
                    <BodyHeaderTypography>Changes to This Privacy Policy:</BodyHeaderTypography>
                    <BodyTypography>
                        {`
We reserve the right to update or change our Privacy Policy at any time. Any changes will be posted on this page with the updated date.

If you have any questions or concerns about our Privacy Policy, please contact us at `}
                        <a href={`mailto:info@${hostname}`} style={{color: 'inherit'}}>
                            {`info@${hostname}`}
                        </a>
                        {`.`}
                    </BodyTypography>
                </Paper>
            </Container>
        </>
    );
}
