name: Build and Deploy
description: "Builds Next.JS App and deploys to Azure Static Web App"

inputs:
    github-token:
        description: "The Github access token"
        required: true
    deploy-token:
        description: "The Azure Static Web App deployment token"
        required: true
    base-app-location:
        description: "The location of the base app when built from mono repo"
        required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build And Deploy
      id: builddeploy
      uses: Azure/static-web-apps-deploy@v1
      env:
        PRE_BUILD_COMMAND: npm install -g pnpm && pnpm install
        CUSTOM_BUILD_COMMAND: pnpm run build && cp -r .next/standalone${{ inputs.base-app-location }}/. .next/standalone
        VERBOSE: true
      with:
        azure_static_web_apps_api_token: ${{ inputs.deploy-token }}
        repo_token: ${{ inputs.github-token }}
        action: "upload"
        app_location: "${{ inputs.base-app-location }}"
        api_location: ""
        output_location: ""
