name: Deploy to Staging Environment
on:
    workflow_dispatch:
    push:
      branches: [develop]
      paths:
        - 'apps/**'
        - 'packages/**'
        - '.github/workflows/deploy-staging.yml'

jobs:
  build-and-deploy:
    name: Build and Deploy Job
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        
      - name: Build and Deploy Static Web App
        uses: ./.github/workflows/composite/build-and-deploy
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          deploy-token: ${{secrets.STAGING_DEPLOY_TOKEN}}
          base-app-location: /apps/web
