name: Deploy to Development Environment
on:
    workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy Job
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        
      - name: Build and Deploy Static Web App
        uses: ./.github/workflows/composite/build-and-deploy
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          deploy-token: ${{secrets.DEV_DEPLOY_TOKEN}}
          base-app-location: /apps/web
